build:
  maxIssues: 10

complexity:
  LongParameterList:
    functionThreshold: 6
  TooManyFunctions:
    thresholdInFiles: 25

style:
  MagicNumber:
    ignoreNumbers: ['-1', '0', '1', '2', '100', '1000']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreConstantDeclaration: true
