param(
  [string]$PreferredSdkDir = ""
)

$ErrorActionPreference = "Stop"

function Normalize-ForwardSlashes([string]$p) { return ($p -replace '\\','/') }

# 1) Decide SDK path
$sdkCandidates = @()
if ($PreferredSdkDir) { $sdkCandidates += $PreferredSdkDir }
$sdkCandidates += @(
  "$env:LOCALAPPDATA\Android\Sdk",
  "$env:USERPROFILE\AppData\Local\Android\Sdk",
  "C:\Android\Sdk"
)

$sdk = $null
foreach ($c in $sdkCandidates) {
  if ($c -and (Test-Path $c)) { $sdk = (Resolve-Path $c).Path; break }
}

# Fallback: try to find adb.exe under the common roots
if (-not $sdk) {
  $roots = @("$env:LOCALAPPDATA\Android", "$env:USERPROFILE\AppData\Local\Android", "C:\Android")
  foreach ($r in $roots) {
    if (-not (Test-Path $r)) { continue }
    $adb = Get-ChildItem -Path $r -Filter adb.exe -Recurse -ErrorAction SilentlyContinue |
           Select-Object -First 1
    if ($adb) {
      $sdk = Split-Path -Parent (Split-Path -Parent $adb.FullName) # ...\Sdk\platform-tools\adb.exe -> ...\Sdk
      break
    }
  }
}

if (-not $sdk) {
  Write-Warning @"
Android SDK not found automatically.
Open Android Studio → Settings → Appearance & Behavior → System Settings → Android SDK,
copy the SDK path, then run:
  .\scripts\windows\fix-android-sdk.ps1 -PreferredSdkDir "C:\Users\<you>\AppData\Local\Android\Sdk"
"@
  exit 2
}

$sdkForward = Normalize-ForwardSlashes $sdk
Write-Host "Using Android SDK at: $sdkForward"

# 2) Write local.properties (forward slashes, ASCII)
$localProps = @"
## Generated by fix-android-sdk.ps1
sdk.dir=$sdkForward
"@
Set-Content -Path "android-app\local.properties" -Value $localProps -Encoding Ascii
Write-Host "Wrote android-app\local.properties"

# 3) Try to install required packages via sdkmanager (if present)
$mgr1 = Join-Path $sdk "cmdline-tools\latest\bin\sdkmanager.bat"
$mgr2 = Join-Path $sdk "cmdline-tools\bin\sdkmanager.bat"
$mgr  = $null
if (Test-Path $mgr1) { $mgr = $mgr1 } elseif (Test-Path $mgr2) { $mgr = $mgr2 }

if ($mgr) {
  & $mgr --version
  & $mgr "platform-tools" "platforms;android-34" "build-tools;34.0.0"
  Write-Host "Ensured: platform-tools, platforms;android-34, build-tools;34.0.0"
} else {
  Write-Warning "cmdline-tools not found. In Android Studio → SDK Manager, install 'Android SDK Command-line Tools (latest)', then re-run this script."
}

Write-Host "Done."


